@baseUrl = http://localhost:3000/api

### Timeouts

GET {{baseUrl}}/wait?timeout=5000


### Timeouts - looong

GET {{baseUrl}}/wait?timeout=50000

### Vars of Vars

@a=5
@b={{a}}
@c={{b}}

GET {{baseUrl}}/echo?param={{c}}

### STATUS - 400

GET {{baseUrl}}/status?code=400

### STATUS - 500

GET {{baseUrl}}/status?code=500

### image

GET {{baseUrl}}/png
