# @env-file ./.env.local

@baseUrl = https://jsonplaceholder.typicode.com


### Request 1

GET {{baseUrl}}/posts
Authorization: Bearer {{TEST_TOKEN_55}}
X-Custom-Header: test
X-Custom-Header2: test

{
  "body": 5,
  "token": "{{TEST_TOKEN_55}}"
}

### Request 2

GET https://google.com/

### Req 3

GET https://dummyjson.com/products/1
